Add $this operator to _determineIfPowerpc calls
Calling _determineIfPowerpc without $this operator will cause a fatal error on macOS.

Fatal error: Uncaught Error: Call to undefined function _determineIfPowerpc()
https://3v4l.org/sog9H